### ISSUE TITLE
Products section

### ISSUE THREAD

**Issue by kvokov** [tabetalt/backoffice#79]
- [x] Products
    - [x] Products listing table
    - [x] Create product form
        - [x] Common settings
        - [x] Decription
        - [x] Inventory
        - [ ] ~~Product Variants~~
        - [ ] ~~Labels and sales~~
    - [x] Update product form
    - [x] Delete product

**Comment by cobraz** [comment]
@kvokov Is this updated as of today?
